name: LintCheck
on:
  
  push:
    branches:
      - master
  pull_request:
    
jobs:
  LintShellCheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Lint check
        uses: azohra/shell-linter@v0.4.0
