name: LintCheck
on:
  
  push:
    branches:
      - master
  pull_request:
    
jobs:
  lint:
    runs-on: debian-latest
    steps:
      - name: Checkout code
      - uses: actions/checkout@v1
      - name: Run Shellcheck
        uses: azohra/shell-linter@latest
        with:
          path: "RPI4-UPSplus-HA-Prep.sh"
